---
- name: Install deps
  # hosts: virtualbox
  hosts: localhost
  roles:
    - role: geerlingguy.java
      become: true
      when: install_java

    - role: geerlingguy.docker
      become: true
      when: install_docker

  vars_files:
    - vars/default_vars.ansible.yml

  tasks:
    - name: Configure repos
      ansible.builtin.import_tasks:
        file: tasks/repos.ansible.yml
      tags: repos

    - name: Install dnf packages
      ansible.builtin.import_tasks:
        file: tasks/dnf_packages.ansible.yml
      tags: dnf_packages

    - name: Install flatpak apps
      ansible.builtin.import_tasks:
        file: tasks/flatpak_apps.ansible.yml
      tags: flatpak_apps

    - name: Configure git
      ansible.builtin.import_tasks:
        file: tasks/git.ansible.yml
      tags: git

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: handlers/handlers.ansible.yml
