---
- name: Install apps & packages
  become: true
  block:
    - name: Install dnf packages
      ansible.builtin.dnf:
        name:
          - git
          - nodejs
          - yarnpkg
          - gnome-tweaks
          - gnome-extensions-app
        state: present

    - name: Install pnpm
      community.general.npm:
        name: pnpm
        global: true

    - name: Install VS Code
      ansible.builtin.dnf:
        name:
          - code
        state: present
      when: install_vscode

    - name: Install Microsoft Edge
      ansible.builtin.dnf:
        name:
          - microsoft-edge-stable
        state: present
      when: install_edge

    - name: Install Discord
      ansible.builtin.dnf:
        name:
          - discord
        state: present
      when: install_discord
