---
- name: Install apps & packages
  become: true
  block:
    - name: Install dnf packages
      ansible.builtin.dnf:
        name:
          - git
          - nodejs
          - yarnpkg
          - gnome-tweaks
        state: present

    - name: Install pnpm
      community.general.npm:
        name: pnpm
        global: true

    - name: Install lt2p VPN module
      ansible.builtin.dnf:
        name:
          - strongswan
          - NetworkManager-l2tp-gnome
        state: present
      notify: 
        - Remove lt2p from netlink blacklist
        - Remove lt2p from ppp blacklist
        - Restart NetworkManager
      when: install_lt2p_vpn_module

    - name: Install VS Code
      ansible.builtin.dnf:
        name:
          - code
        state: present
      when: install_vscode

    - name: Install Microsoft Edge
      ansible.builtin.dnf:
        name:
          - microsoft-edge-stable
        state: present
      when: install_edge

    - name: Install Discord
      ansible.builtin.dnf:
        name:
          - discord
        state: present
      when: install_discord
