---
- name: Install dnf packages
  ansible.builtin.dnf:
    name:
      - git
      - nodejs
      - yarnpkg
      - gnome-tweaks
      - gnome-extensions
      - microsoft-edge-stable
      - code
      - playonlinux
    state: present
  become: true

- name: Install pnpm
  community.general.npm:
    name: pnpm
    global: true
  become: true
